services:
  - type: web
    name: muyacon-webhook
    env: node
    buildCommand: npm install
    startCommand: node api/payments/chapa/webhook.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: CHAPA_WEBHOOK_SECRET
        value: qwertyuil@1A
